mutation CreateProject($name: String!, $description: String!) {
  createProject(name: $name, description: $description) {
    message
    success
  }
}

mutation DeleteProject($id: ID!) {
  deleteProject(id: $id) {
    message
    success
  }
}