query GetMe {
  me {
    email
    credits
    id
    name
  }
}

query Projects {
  projects {
    name
    id
    description
    updatedAt
    documents {
      description
      id
      title
      lastModified
      isTrashed
      transcriptionType
      transcriptionStatus
    }
  }
}

query GenerateWordFileFromHTML($html: String!) {
  generateWordFileFromHTML(html: $html) {
    expiresAtUnixSeconds
    url
  }
}

query mePinnedProjects {
  pinnedProjects {
    id
    name
    documents {
      id
    }
  }
}

query SupportedLanguages {
  supportedLanguages {
    languageName
  }
}
